{
 "title": "Subsquid",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "subsquid_job_name", "label": "Subsquid Job Name", "query": "subsquid" },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "label_values(worker_info_info{job=\"$subsquid_job_name\"}, instance)"
    }
   },
   { "name": "node_job_name", "query": "node" }
  ]
 },
 "panels": [
  { "title": "Aggregate Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_status{job=\"$subsquid_job_name\",instance=~\"$instances\"}) by (worker_status)",
     "legendFormat": "{{worker_status}}"
    }
   ]
  },
  {
   "title": "Worker List",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(worker_info_info{job=\"$subsquid_job_name\",instance=~\"$instances\"}) by (instance, peer_id, version)"
    }
   ]
  },
  {
   "title": "Query Traffic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(query_result_size_bytes_sum{job=\"$subsquid_job_name\",instance=~\"$instances\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Download Traffic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(downloaded_bytes_sum{job=\"$subsquid_job_name\",instance=~\"$instances\"}[$__range]))",
     "legendFormat": "Download Bandwith"
    }
   ]
  },
  {
   "title": "Data Stored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stored_bytes{job=\"$subsquid_job_name\",instance=~\"$instances\"})"
    }
   ]
  },
  { "title": "$instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instances" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_status{job=\"$subsquid_job_name\",instance=~\"$instances\"} > 0",
     "legendFormat": "{{worker_status}}"
    }
   ]
  },
  {
   "title": "Query Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(query_result_size_bytes_sum{job=\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval]) / rate(query_result_size_bytes_count{job=\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Query Bandwith"
    },
    { "expr": "query_" }
   ]
  },
  {
   "title": "Query Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(num_bad_requests_total{job=~\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "Query Errors"
    },
    {
     "expr": "rate(num_successful_queries_total{job=~\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "Successful Queries"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_info_info{job=\"$subsquid_job_name\",instance=~\"$instances\"} > 0",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Download Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(downloaded_bytes_sum{job=\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval]) / rate(downloaded_bytes_count{job=\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval])) by (instance) ",
     "legendFormat": "Download Bandwith"
    }
   ]
  },
  {
   "title": "Download Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(num_download_errors_total{job=~\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "Download Errors"
    },
    {
     "expr": "rate(num_successful_downloads_total{job=~\"$subsquid_job_name\",instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "Successful Downloads"
    }
   ]
  },
  {
   "title": "Data Stored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(stored_bytes{job=\"$subsquid_job_name\",instance=~\"$instances\"})",
     "legendFormat": "Data Stored"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instances\",job=\"$node_job_name\",device!~\"lo|veth.*|cni-.*\"}[$__rate_interval]) *-1",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instances\",job=\"$node_job_name\",device!~\"lo|veth.*|cni-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instances\",job=\"$node_job_name\"} - node_memory_MemFree_bytes{instance=~\"$instances\",job=\"$node_job_name\"} - (node_memory_Cached_bytes{instance=~\"$instances\",job=\"$node_job_name\"} + node_memory_Buffers_bytes{instance=~\"$instances\",job=\"$node_job_name\"} + node_memory_SReclaimable_bytes{instance=~\"$instances\",job=\"$node_job_name\"})",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instances\",job=\"$node_job_name\"}",
     "legendFormat": "Memory Total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$instances\",job=~\"$node_job_name\"}[$__rate_interval])) - sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$instances\",job=~\"$node_job_name\", mode=\"idle\"}[$__rate_interval]))) / sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$instances\",job=~\"$node_job_name\"}[$__rate_interval]))",
     "legendFormat": "CPU usage"
    }
   ]
  }
 ]
}